// Date: 12/22/2016 5:09:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelmachinearm_swivlejoint extends ModelBase
{
  //fields
    ModelRenderer SwivelJointBase;
    ModelRenderer SwivelJointConector1;
    ModelRenderer SwivelJointConector2;
    ModelRenderer SwivelJointConector3;
    ModelRenderer SwivelJointConector4;
  
  public Modelmachinearm_swivlejoint()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      SwivelJointBase = new ModelRenderer(this, 0, 0);
      SwivelJointBase.addBox(-4F, -1F, -4F, 8, 2, 8);
      SwivelJointBase.setRotationPoint(0F, 0F, 0F);
      SwivelJointBase.setTextureSize(64, 32);
      SwivelJointBase.mirror = true;
      setRotation(SwivelJointBase, 0F, 0F, 0F);
      SwivelJointConector1 = new ModelRenderer(this, 0, 11);
      SwivelJointConector1.addBox(0F, 0F, 0F, 1, 2, 6);
      SwivelJointConector1.setRotationPoint(-2F, -3F, -3F);
      SwivelJointConector1.setTextureSize(64, 32);
      SwivelJointConector1.mirror = true;
      setRotation(SwivelJointConector1, 0F, 0F, 0F);
      SwivelJointConector2 = new ModelRenderer(this, 0, 11);
      SwivelJointConector2.addBox(0F, 0F, 0F, 1, 2, 6);
      SwivelJointConector2.setRotationPoint(1F, -3F, -3F);
      SwivelJointConector2.setTextureSize(64, 32);
      SwivelJointConector2.mirror = true;
      setRotation(SwivelJointConector2, 0F, 0F, 0F);
      SwivelJointConector3 = new ModelRenderer(this, 0, 20);
      SwivelJointConector3.addBox(0F, 0F, 0F, 1, 4, 4);
      SwivelJointConector3.setRotationPoint(1F, -7F, -2F);
      SwivelJointConector3.setTextureSize(64, 32);
      SwivelJointConector3.mirror = true;
      setRotation(SwivelJointConector3, 0F, 0F, 0F);
      SwivelJointConector4 = new ModelRenderer(this, 0, 20);
      SwivelJointConector4.addBox(0F, 0F, 0F, 1, 4, 4);
      SwivelJointConector4.setRotationPoint(-2F, -7F, -2F);
      SwivelJointConector4.setTextureSize(64, 32);
      SwivelJointConector4.mirror = true;
      setRotation(SwivelJointConector4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    SwivelJointBase.render(f5);
    SwivelJointConector1.render(f5);
    SwivelJointConector2.render(f5);
    SwivelJointConector3.render(f5);
    SwivelJointConector4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
